/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.List;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import project_point_of_sales.Transaksi;
import project_point_of_sales.koneksi;
/**
 *
 * @author User
 */
public final class Frame_Invoice extends javax.swing.JFrame {
    
    ArrayList<Integer> idBarangList = new ArrayList<>();
    ArrayList<String> namaBarangList = new ArrayList<>();
    ArrayList<Integer> hargaBarangList = new ArrayList<>();
    ArrayList<Integer> jumlahBarangList = new ArrayList<>();
    ArrayList<Integer> hargaTotalList = new ArrayList<>();
    
    /**
     * Creates new form Frame_Invoice
     */
    koneksi kn = new koneksi();
    Connection kon = kn.getKoneksi();
    
    public void getDetailBelanja(int id_trans) {
        System.out.println("id trans getDetail : " + id_trans);
        try {
            Statement stmt = (Statement) kn.getKoneksi().createStatement();
            String sql = "SELECT data_detailbelanja.id_barang,data_detailbelanja.nama_Barang,data_detailbelanja.Harga_jual,data_detailbelanja.jumlah_item,data_detailbelanja.harga_Total FROM transaksi INNER JOIN data_detailbelanja ON transaksi.id=data_detailbelanja.id_transaksi WHERE data_detailbelanja.id_transaksi='"+id_trans+"'";
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()){
                idBarangList.add(rs.getInt("id_barang"));
                namaBarangList.add(rs.getString("nama_Barang"));
                hargaBarangList.add(rs.getInt("Harga_jual"));
                jumlahBarangList.add(rs.getInt("jumlah_item"));
                hargaTotalList.add(rs.getInt("harga_Total"));
            }
        } catch (SQLException sqle) {
            System.out.println(sqle);
        }
    }
    
    private Transaksi transaksi;
    
    public Frame_Invoice() {
        initComponents();
    }
    public Frame_Invoice(Transaksi transaksi) {
        initComponents();
        this.transaksi = transaksi;
        System.out.println("trans id " + transaksi.getId() + " total : " + transaksi.getTotal());
        int id_trans = transaksi.getId();
        getDetailBelanja(id_trans);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("INVOICE");

        area.setColumns(20);
        area.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Print Invoice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Generate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addGap(205, 206, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
//        try {
//            area.print();
//        } catch (Exception e) {
//        }
            area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Frame_Invoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
//        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
//        System.out.println("trans id " + transaksi.getId() + " total : " + transaksi.getTotal() + transaksi.getWaktu() + transaksi.getId_cashier());
        area.setText("*****************************************\n");
        area.setText(area.getText()+"\t\tINVOICE                      \n");
        area.setText(area.getText()+"*****************************************\n");
        area.setText(area.getText()+ transaksi.getWaktu() + "\n\n");
        area.setText(area.getText()+"ID Transaksi\t: " +String.valueOf(transaksi.getId() + "\n"));
        area.setText(area.getText()+"ID Cashier\t: " +String.valueOf(transaksi.getId_cashier()) + "\n");
        area.setText(area.getText()+"ID Customer\t: " +String.valueOf(transaksi.getId_customer()) + "\n");
        area.setText(area.getText()+ "--------------------------------------------------");
        area.setText(area.getText()+"\nDetail Belanja :\n\n");
        for (int i = 0; i < namaBarangList.size(); i++) {
            area.setText(area.getText() + namaBarangList.get(i) + "\t" + jumlahBarangList.get(i) + "\t" + "Rp." + hargaBarangList.get(i) + "\t" + "Rp." + hargaTotalList.get(i) + "\n");
        }
        area.setText(area.getText()+"\nTotal \t\t\t:" + "Rp."+ String.valueOf(transaksi.getTotal()) + "\n");
        area.setText(area.getText()+"Tipe Pembayaran :  " +String.valueOf(transaksi.getPembayaran()) + "\n");
//        area.setText("=======================================================");
//        area.setText(area.getText() + id_cashier);
//        area.setText(String.valueOf(transaksi.getId_cashier()));
//        area.setText(String.valueOf(transaksi.getId_customer()));
//        area.setText(transaksi.getWaktu());
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
